# Generated by Django 4.0.6 on 2022-07-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_pk',
        ),
    ]
