# Generated by Django 4.0.6 on 2022-07-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_profile_user_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_pk',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
