# Generated by Django 4.1 on 2022-08-22 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="TITLE")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="community/",
                        verbose_name="IMAGE",
                    ),
                ),
                ("content", models.TextField(verbose_name="CONTENT")),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DT"),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now=True, verbose_name="UPDATE DT"),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="CONTENT")),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DT"),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now=True, verbose_name="UPDATE DT"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.post",
                    ),
                ),
            ],
        ),
    ]
